### ISSUE TITLE
'bdsync --patch' don't work

### ISSUE THREAD

**Issue by romankspb** [rolffokkens/bdsync#2]
~]#  zcat patch.bdsync.gz | bdsync -p /dev/vg_dst/lv_dst
Bad number of arguments

**Comment by rolffokkens** [comment]
Thx, updated http://bdsync.rolf-fokkens.nl/ as well.

**Comment by jmcclelland** [comment]
Thanks for making the change.
I found one  more possible documentation bug.
gzip < DEV.bdsync.gz 
Doesn't work - at least not with gzip 1.6-4 on Debian jessie.
Instead, both of the following work
gzip -d < DEV.bdsync.gz 
gunzip -c < DEV.bdsync.gz 

Maybe it's a small difference in gzip behavior between different flavors of unix?

**Comment by rolffokkens** [comment]
This definitely missed a "-d", thx. Fixed it.
