### ISSUE TITLE
bdsync for windows server

### ISSUE THREAD

**Issue by lcami** [rolffokkens/bdsync#27]
Hi Everyone, this is not exactly an issue but a feature/port request.

I have tested bdsync on Linux and it runs great and I could actually sync a server's block device into an image file which I then imported into a VM in a different location.

Would it be possible to do this for Windows servers while the servers are still powered on?
If it is possible what would it require?
My plan is to build a disaster recovery / business continuity solution around bdsync and would like to know if the same software can be ported/written to windows

Thanks

**Comment by hnz101** [comment]
Unfortunatly it doesn't compile under cygwin. Would love to use bdsync for syncing VM-Images on my Windows Desktop.

```
In file included from bdsync.c:56:
bdsync.c: In function ‘handle_err’:
bdsync.c:435:26: warning: array subscript has type ‘char’ [-Wchar-subscripts]
  435 |             if (!isprint(*rp)) {
      |                          ^~~
bdsync.c: In function ‘opendev’:
bdsync.c:1724:29: error: ‘O_LARGEFILE’ undeclared (first use in this function)
 1724 |     fd = open (dev, flags | O_LARGEFILE);
      |                             ^~~~~~~~~~~
```
