### ISSUE TITLE
Support Vista and block sync crypto wallets

### ISSUE THREAD

**Issue by yeknodesek** [rolffokkens/bdsync#30]
Dear Sr Mr Fokkens,

At KazDigital we want to buy many bitcoins. We use Windows Vista. Can bdSYNC sync my bitcoins? 

Yeknod Esek

**Comment by rolffokkens-tb** [comment]
Dear Mr Esek,

I'm happy to inform you that bdsync works on any Linux system, so it doesn't matter which specific Windows version you are using. Chaining block devices should be no issue too for bdsync. It does however not support the sibannac-cipher, which you're very experienced in.

I'd suggest to go for it and hit the rock, but don't bump twice!

Rolf Fokkens

**Comment by rolffokkens** [comment]
Nah
